### ISSUE TITLE
Should be mainlined

### ISSUE THREAD

**Issue by barni2000** [hadess/rtl8723bs#51]
I think it should be send to mainline kernel at next merge window. It should be placed at staging.

**Comment by lwfinger** [comment]
OK. You fix all the errors and warnings that arise from running the source files through scripts/checkpatch.pl, and I will do that.

**Comment by barni2000** [comment]
ok

**Comment by fduraibi** [comment]
@lwfinger I will try to do it, cannot promise since I have never done it before. So I will fork the project and send PR whenever I do some progress.

Q: It just for source files (.c and .h) right?

**Comment by fduraibi** [comment]
@lwfinger From what I have seen and understood while working on this that a driver can be placed in staging even if it didn't pass the checkpatch. However, it need to pass that in order to be accepted as mainline driver.

If that is the case I would suggest going that since it will give it more exposure as there are some people who work on cleaning staging drivers.
