### ISSUE TITLE
Newer versions of the driver

### ISSUE THREAD

**Issue by lwfinger** [hadess/rtl8723bs#98]
Anthony Wong at Canonical is investigating making this driver as part of Ubuntu's kernel. As a part of this activity, he has gotten newer drivers from Realtek. If anyone is interested in testing them, versions 4.3.16, 4.4.0 and 4.4.1 are available from https://github.com/anthonywong/rtl8723bs.

**Comment by joerg-krause** [comment]
Nice! I guess asking about a Changelog is useless.

**Comment by speculatrix** [comment]
it could be worse, it could be a Mediatek chip!

**Comment by lwfinger** [comment]
I once asked Realtek for read access to their SVN repository. My request was ignored.

You could run diff on the various versions, but they have a habit of making a lot of trivial changes that obscure the important differences.

**Comment by hzulla** [comment]
This is great news. Thanks @anthonywong!

**Comment by hadess** [comment]
The driver is now upstream. Hopefully, Realtek will start cleaning the upstreamed driver instead of spinning messy driver updates. See commit 3bb1d33.

If you feel courageous, compare the newer versions of the driver to the original driver dump in this repository, and check whether the changes are still relevant to newer versions of the driver, upstream.
